apiVersion: apps/v1
kind: Deployment
metadata:
  name: authregister-deployment
spec:
  selector:
    matchLabels:
      app: authregister
  replicas: 1
  template:
    metadata:
      labels:
        app: authregister
    spec:
      containers:
        - name: authregister
          image: elmachkouriimane/authregister:latest
          ports:
            - containerPort: 8083
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_READINESSTATE_ENABLED
              value: "true"
            - name: MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED
              value: "true"
            - name: SERVER_SHUTDOWN
              value: "graceful"

          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: authregister
  name: authregister-svc
spec:
  selector:
    app: authregister
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
status:
  loadBalancer: {}
