apiVersion: apps/v1
kind: Deployment
metadata:
  name: internship-model-deployment
spec:
  selector:
    matchLabels:
      app: internship-model
  replicas: 1
  template:
    metadata:
      labels:
        app: internship-model
    spec:
      containers:
        - name: internship-model
          image: essalhisara111/recommendation:internship_ml
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: internship-model
  name: internship-model-svc
spec:
  selector:
    app: internship-model
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
status:
  loadBalancer: {}
