spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret : supersecret
bezkoder:
  app:
    jwtExpirationMs: 3600000
server:
  port: 8083